#! /bin/bash

set -euxo pipefail

# switch branch
BRANCH=$(pacman-mirrors --get-branch)
if ${BRANCH} != unstable
then
    sudo pacman-mirrors --api --set-branch unstable
    sudo pacman-mirrors --fasttrack 5
    sudo pacman -Syyu --noconfirm
fi

# pacman
sudo pacman -Syu --noconfirm git \
    base-devel \
    stow \
    vim \
    tmux \
    zsh \
    zip \
    caffeine \
    docker \
    docker-compose \
    alacritty \
    chromium \
    go \
    nodejs \
    npm \
    yay \
    code

# aur
yay -Syu --noconfirm antigen-git \
    gopro-tools-git

