#! /bin/bash

set -euxo pipefail

# pacman
sudo pacman -Sy --noconfirm git \
    base-devel \
    stow \
    vim \
    tmux \
    zsh \
    zip \
    caffeine \
    docker \
    docker-compose \
    alacritty \
    chromium \
    go \
    yay \
    aws-cli \
    jdk-openjdk \
    gradle \
    intellij-idea-community-edition \
    dotnet-sdk \
    vlc \
    krita

# aur
yay -Sy --noconfirm antigen-git \
    gopro-tools-git \
    nvm \
    visual-studio-code-bin \
    surfshark-vpn

