#! /bin/bash

set -euxo pipefail

# pacman
sudo pacman -Syu --noconfirm git \
    base-devel \
    stow \
    vim \
    tmux \
    zsh \
    zip \
    caffeine \
    docker \
    docker-compose \
    alacritty \
    chromium \
    go \
    yay \
    code \
    aws-cli \
    jdk-openjdk \
    gradle

# aur
yay -Syu --noconfirm antigen-git \
    gopro-tools-git \
    nvm

# java
sudo archlinux-java set java-13-openjdk

